# Generated by Django 4.1.1 on 2022-09-18 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('C', 'Controller'), ('M', 'Memory Card'), ('E', 'External Hard Drive')], default='C', max_length=1)),
                ('number', models.IntegerField()),
                ('date_purchased', models.DateField(verbose_name='Date purchased')),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.console')),
            ],
        ),
    ]
