# Generated by Django 4.1.1 on 2022-09-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_accessory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('release_year', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='accessory',
            options={'ordering': ['-date_purchased']},
        ),
    ]
