# Generated by Django 4.1.1 on 2022-09-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_game_alter_accessory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='console',
            name='games',
            field=models.ManyToManyField(to='main_app.game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_year',
            field=models.IntegerField(verbose_name='Release Year'),
        ),
    ]
